### ISSUE TITLE
Missing Template.js

### ISSUE THREAD

**Issue by zeuben** [eversign/eversign-node-sdk#4]
in Request.js you're dynamically requiring modules:

https://github.com/eversign/eversign-node-sdk/blob/c714026fd4f71f9663f35383c0252197c5a2307b/lib/Request.js#L92

However Template.js is missing from the lib directory.

So when executing:
```
const exec = async () => {
  getTemplate(relayTemplateId).then((template) => {
    console.log('template', template.toObject());
  });
};
```

it throws
```
module.js:491
    throw err;
    ^

Error: Cannot find module './Template'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Request._callback (/Users/xxx/spikes/eversign/local/server/node_modules/eversign/lib/Request.js:92:22)
    at Request.self.callback (/Users/xxx/spikes/eversign/local/server/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/xxx/spikes/eversign/local/server/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/xxx/spikes/eversign/local/server/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)

```

It looks like DocumentTemplate is the closest match.
Can you fix?

**Comment by dominikkukacka** [comment]
We just released 1.3.1 which should fix this bug.
Thanks
