### ISSUE TITLE
uncaughtException thrown if Response body isn't valid JSON

### ISSUE THREAD

**Issue by mikeroelens** [eversign/eversign-node-sdk#66]
In a couple of places in Request.js `JSON.parse` is called in an unsafe manner.

Locations:
https://github.com/eversign/eversign-node-sdk/blob/d877a074b6caa44081317813b70cf3332bd9d39d/lib/Request.js#L107
https://github.com/eversign/eversign-node-sdk/blob/d877a074b6caa44081317813b70cf3332bd9d39d/lib/Request.js#L141

When `body` isn't valid JSON we receive the following error as an uncaughtException in Node:
```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/srv/node_modules/eversign/lib/Request.js:141:22)
    at Request.self.callback (/srv/node_modules/request/request.js:185:22)
    at Request.emit (node:events:526:28)
    at Request.emit (node:domain:475:12)
    at Request.<anonymous> (/srv/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:526:28)
    at Request.emit (node:domain:475:12)
    at IncomingMessage.<anonymous> (/srv/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:645:28)
    at IncomingMessage.emit (node:events:538:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

based on "Unexpected token <" it seems as though the Eversign API is returning HTML instead of the expected JSON.

**Expected Behaviour:** There is a `try/catch` around `JSON.parse` and when the parsing fails the Promise is rejected instead of throwing an unexpected exception

**Comment by mikeroelens** [comment]
Please let me know if you'd like me to create a PR to address this, happy to do so

**Comment by milanlatinovic** [comment]
Hi @mikeroelens, thanks for reporting this.

If you can create quick MR, tag me as a reviewer and I'll check it out.
